<a href="https://colab.research.google.com/github/KarabiGoswami/Projects/blob/main/Image_recognition_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Image Recognition
Darpan Goswami


In [ ]:
from sklearn.metrics import f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy as np
import math
import imutils
import time
import cv2
import os
from imutils import paths

In [ ]:
def face_detection(image):

    #cascadePath = "drive/MyDrive/Colab Notebooks/haarcascade_frontalface_default.xml"
    cascadePath = "haarcascade_frontalface_default.xml"
    detector = cv2.CascadeClassifier(cascadePath)

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    rects = detector.detectMultiScale(gray, scaleFactor=1.05, minNeighbors=10, minSize=(30, 30))

    return rects

In [ ]:
from imutils import paths
imagePaths = list(paths.list_images('celeb-data'))
for p in imagePaths:
    print(p)
    print(p.split(os.path.sep)[3])
names = [p.split(os.path.sep)[-2] for p in imagePaths]
print (len(names))
(names , counts) = np.unique(names , return_counts = True)
print (len(names))
names = names.tolist()

celeb-data\celeb-data\George_Clonney\George_Clooney_1.jpg
George_Clooney_1.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_10.jpg
George_Clooney_10.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_11.jpg
George_Clooney_11.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_13.jpg
George_Clooney_13.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_14.jpg
George_Clooney_14.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_15.jpg
George_Clooney_15.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_16.jpg
George_Clooney_16.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_18.jpg
George_Clooney_18.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_19.jpg
George_Clooney_19.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_2.jpg
George_Clooney_2.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_20.jpg
George_Clooney_20.jpg
celeb-data\celeb-data\George_Clonney\George_Clooney_22.jpg
George_Clooney_22.jpg
celeb-data\celeb-data\George_Clo

In [ ]:
def load_face_dataset(inputPath, minSamples = 15):
  # get all the image paths in the dataset folder structure and grab
  # the name(i.e. groundtruth) of all the images and count each of them
  # and then put all of the groundtruths into a list
    imagePaths = list(paths.list_images(inputPath))
    names = [p.split(os.path.sep)[-2] for p in imagePaths]
    #to store the repeated names or values only ones ,i.e., uniquely
    (names , counts) = np.unique(names , return_counts = True)
    names = names.tolist()

    faces = []
    labels = []

  # loop over all of the image paths
    for imagePath in imagePaths:
    # read the image and grab the image label
        image = cv2.imread(imagePath)
        name = imagePath.split(os.path.sep)[-2]

    # check whether the count of this specific label is
    # below our minSamples threshold or not
        if counts[names.index(name)] < minSamples:
              continue

    # perform face detection
        boxes = face_detection(image)

    # loop over the bounding boxes
        for (x , y , w , h) in boxes:
            try:
                # extract the face ROI, resize it and convert
                # it into grayscale format
                faceROI = image[y:y+h , x:x+w]#we are trying to extract using this image[y:y+h, x:x+w]
                faceROI = cv2.resize(faceROI , (47 , 62))#setting one common size for all faces
                faceROI = cv2.cvtColor(faceROI , cv2.COLOR_BGR2GRAY)
                #each afce will be of size - (47, 62)
                # update the faces and labels list
                faces.append(faceROI)
                labels.append(name)
            except:
                continue
    # convert and store the faces and labels lists into Numpy array
    faces = np.array(faces)
    labels = np.array(labels)
    print (faces.shape)
    print (labels.shape)
    print (labels)
    return (faces , labels)

In [ ]:
# extract faces and label from dataset
(faces , labels) = load_face_dataset('celeb-data/celeb-data', minSamples=15)

(93, 62, 47)
(93,)
['George_Clonney' 'George_Clonney' 'George_Clonney' 'George_Clonney'
 'George_Clonney' 'George_Clonney' 'George_Clonney' 'George_Clonney'
 'George_Clonney' 'George_Clonney' 'George_Clonney' 'George_Clonney'
 'George_Clonney' 'George_Clonney' 'George_Clonney' 'George_Clonney'
 'George_Clonney' 'George_Clonney' 'George_Clonney' 'George_Clonney'
 'George_Clonney' 'George_Clonney' 'George_Clonney' 'George_Clonney'
 'George_Clonney' 'George_Clonney' 'Matt_Damon' 'Matt_Damon' 'Matt_Damon'
 'Matt_Damon' 'Matt_Damon' 'Matt_Damon' 'Matt_Damon' 'Matt_Damon'
 'Matt_Damon' 'Matt_Damon' 'Matt_Damon' 'Matt_Damon' 'Matt_Damon'
 'Matt_Damon' 'Matt_Damon' 'Matt_Damon' 'Matt_Damon' 'Matt_Damon'
 'Matt_Damon' 'Matt_Damon' 'Matt_Damon' 'Nicolas_Cage' 'Nicolas_Cage'
 'Nicolas_Cage' 'Nicolas_Cage' 'Nicolas_Cage' 'Nicolas_Cage'
 'Nicolas_Cage' 'Nicolas_Cage' 'Nicolas_Cage' 'Nicolas_Cage'
 'Nicolas_Cage' 'Nicolas_Cage' 'Nicolas_Cage' 'Nicolas_Cage'
 'Nicolas_Cage' 'Nicolas_Cage' 'Nicolas_Ca

Assignment

In [ ]:
# encode the labels
le = LabelEncoder()
labels = le.fit_transform(labels)

print (faces.shape)

new_faces = faces.reshape(93,62*47)
print(new_faces)
# split the data into training and test set
X_train , x_test , Y_train , y_test = train_test_split(new_faces , labels , test_size = 0.2, random_state = 7)

X_train = X_train.reshape((74, 62*47))
Y_train = Y_train.reshape((74, ))


# Import MLPClassifer
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,Y_train)

(93, 62, 47)
[[167 160 147 ... 232 231 228]
 [ 75 168 140 ...  13  31  38]
 [219 220 211 ... 209  38  12]
 ...
 [103  32  24 ... 179 180 183]
 [ 58  95 107 ... 165 164 170]
 [ 77  75  71 ...  48  51  55]]


MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5)

In [ ]:
#Testing the Model

prediction = clf.predict(x_test)

# show the classification report

print(classification_report(y_test, prediction))
print("Accuracy:", accuracy_score(prediction, y_test))

              precision    recall  f1-score   support

           0       0.54      1.00      0.70         7
           1       0.00      0.00      0.00         5
           2       1.00      0.80      0.89         5
           3       1.00      1.00      1.00         2

    accuracy                           0.68        19
   macro avg       0.63      0.70      0.65        19
weighted avg       0.57      0.68      0.60        19

Accuracy: 0.6842105263157895


C:\Users\mukht\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mukht\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mukht\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
